/**
 * besshi-pdf-styles — 비상장주식 평가서(별지 부표3) PDF 공유 색상·스타일
 *
 * `UnlistedStockBesshiPdfDocument.tsx`에서 추출 (800줄 정책 — Page5 3열 정합 선행 분리).
 * 페이지 컴포넌트를 참조하지 않는 순수 스타일 모듈 (순환 의존 없음).
 */

import { StyleSheet } from "@react-pdf/renderer";
import { BESSHI_FONT_STACK } from "./fonts";

export const C = {
  black: "#000000",
  gray100: "#f3f4f6",
  gray50: "#f9fafb",
  yellow50: "#fefce8",
  emerald50: "#ecfdf5",
  rose50: "#fef2f2",
  rose700: "#b91c1c",
  amber50: "#fffbeb",
  amber700: "#b45309",
};

export const s = StyleSheet.create({
  page: {
    // NanumGothic 본문 + enclosed 글리프 fallback (①~⑲·㉠㉡·㉮㉯) — 저바이트 절단 폴백 정정
    fontFamily: [...BESSHI_FONT_STACK],
    fontSize: 9,
    color: C.black,
    padding: 30,
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: { fontSize: 8, textAlign: "right", marginBottom: 6 },
  sectionTitle: {
    fontSize: 10,
    fontWeight: 700,
    borderLeftWidth: 3,
    borderLeftColor: C.black,
    borderLeftStyle: "solid",
    paddingLeft: 5,
    marginTop: 8,
    marginBottom: 4,
  },
  // 표 컬럼 (View flexDirection: row)
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: C.gray100,
    borderTopWidth: 0.5,
    borderTopColor: C.black,
    borderTopStyle: "solid",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  cellNum: {
    width: 30,
    padding: 3,
    fontSize: 8,
    textAlign: "center",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  cellLabel: {
    flex: 1,
    padding: 3,
    fontSize: 8,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  cellAmount: {
    width: 100,
    padding: 3,
    fontSize: 8,
    textAlign: "right",
  },
  cellSubtract: {
    width: 80,
    padding: 3,
    fontSize: 8,
    textAlign: "right",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  // 제2쪽 4. 순자산가액 — 공식 2단 레이아웃 (값 1열 + 회색 참조열)
  p2UnitRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  p2Unit: { fontSize: 8 },
  p2Value: {
    width: 110,
    padding: 3,
    fontSize: 8,
    textAlign: "right",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p2Ref: {
    width: 120,
    padding: 3,
    fontSize: 7,
    color: "#6b7280",
    backgroundColor: C.gray100,
  },
  p2TopBorder: { borderTopWidth: 1, borderTopColor: C.black, borderTopStyle: "solid" },
  // 제4쪽 5. 평가차액 — 공식 좌우 2블록 (자산금액 │ 부채금액, 각 4열)
  p4HeaderBar: {
    flexDirection: "row",
    borderWidth: 0.5,
    borderColor: C.black,
    borderStyle: "solid",
  },
  p4HeaderL: {
    flex: 1,
    padding: 3,
    fontSize: 8,
    fontWeight: 700,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p4HeaderR: { flex: 1, padding: 3, fontSize: 7, textAlign: "right" },
  p4BlockTitle: {
    flex: 1,
    padding: 3,
    fontSize: 8,
    fontWeight: 700,
    textAlign: "center",
    backgroundColor: C.gray100,
  },
  p4Name: {
    flex: 2,
    padding: 2,
    fontSize: 7,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p4NameDiv: {
    flex: 2,
    padding: 2,
    fontSize: 7,
    borderLeftWidth: 1.5,
    borderLeftColor: C.black,
    borderLeftStyle: "solid",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p4Amt: {
    flex: 1.4,
    padding: 2,
    fontSize: 7,
    textAlign: "right",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p4GuideTitle: {
    fontSize: 8,
    fontWeight: 700,
    textAlign: "center",
    backgroundColor: C.gray100,
    padding: 4,
    marginTop: 10,
  },
  p4GuideBody: { fontSize: 7, padding: 3, lineHeight: 1.4 },
  p4GuideItem: { fontSize: 7, paddingHorizontal: 6, paddingVertical: 1, lineHeight: 1.4 },
  // 제5쪽 6. 영업권 — 공식 3열 [번호+라벨][금액][산식·참조·회색]
  p5LabelCell: {
    flex: 1,
    padding: 3,
    flexDirection: "column",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p5LabelMain: { fontSize: 8 },
  p5LabelSub: { fontSize: 7, color: "#6b7280" },
  p5Amt: {
    width: 100,
    padding: 3,
    fontSize: 8,
    textAlign: "right",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
  },
  p5Col3: { width: 140, padding: 3, fontSize: 7, textAlign: "center" },
  p5Col3Gray: { width: 140, padding: 3, fontSize: 7, backgroundColor: C.gray100 },
  // 제6쪽 7. 순손익액 — 21항목 전개 + 좌측 그룹 라벨 (rowspan = flex-row wrapper)
  p6FyCol: {
    width: 78,
    padding: 2,
    fontSize: 7,
    textAlign: "right",
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  p6Item: {
    flex: 1,
    padding: 2,
    fontSize: 7,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  p6Spacer: {
    width: 44,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  p6GroupLabel: {
    width: 44,
    padding: 2,
    fontSize: 7,
    textAlign: "center",
    justifyContent: "center",
    backgroundColor: C.gray50,
    borderRightWidth: 0.5,
    borderRightColor: C.black,
    borderRightStyle: "solid",
    borderBottomWidth: 0.5,
    borderBottomColor: C.black,
    borderBottomStyle: "solid",
  },
  p6TextLine: { fontSize: 8, marginTop: 4 },
  emphasized: { backgroundColor: C.yellow50, fontWeight: 700 },
  groupRow: { backgroundColor: C.gray50, fontWeight: 700 },
  finalRow: {
    backgroundColor: C.emerald50,
    fontWeight: 700,
    borderTopWidth: 1,
    borderTopColor: C.black,
    borderTopStyle: "solid",
  },
  badge: {
    fontSize: 8,
    backgroundColor: C.rose50,
    borderWidth: 0.5,
    borderColor: "#fecaca",
    borderStyle: "solid",
    padding: 4,
    color: C.rose700,
    marginTop: 4,
  },
  amberFooter: {
    fontSize: 8,
    backgroundColor: C.amber50,
    borderWidth: 0.5,
    borderColor: "#fde68a",
    borderStyle: "solid",
    padding: 4,
    color: C.amber700,
    marginTop: 4,
  },
  metaRow: { flexDirection: "row", marginBottom: 2 },
  metaLabel: { width: 100, fontSize: 8, fontWeight: 700, backgroundColor: C.gray100, padding: 4 },
  metaValue: { flex: 1, fontSize: 8, padding: 4, borderBottomWidth: 0.3, borderBottomColor: C.black, borderBottomStyle: "solid" },
  footer: {
    fontSize: 7,
    textAlign: "center",
    color: "#6b7280",
    marginTop: 12,
  },
});
