/**
 * AssetForm 기본값 팩토리 + sessionStorage 마이그레이션
 * calc-wizard-asset.ts 800줄 정책에 따라 분리 (2026-05-04).
 */

import { MIXED_USE_DEFAULTS } from "./calc-wizard-asset-mixed-use";
import { RESIDENCE_DEFAULTS } from "./calc-wizard-asset-residence";
import { CARRYOVER_DEFAULTS } from "./calc-wizard-asset-carryover";
import type { AssetForm } from "./calc-wizard-asset";

// migrateAsset은 800줄 정책으로 calc-wizard-asset-migrate.ts에 분리 — 하위 호환 위해 re-export(import 경로 무변경)
export { migrateAsset } from "./calc-wizard-asset-migrate";

/** 장기임대주택 거주주택 비과세 특례 초기값 (소령 §155⑳) */
export const RENTAL_HOUSING_EXCEPTION_DEFAULTS: AssetForm["rentalHousingException"] = {
  applyException: false,
  scenario: 'A',
  rentalUnits: [],
  priorResidenceTransferDate: undefined,
  standardPriceAtAcquisitionForPhrp: undefined,
  standardPriceAtPriorTransfer: undefined,
  standardPriceAtTransferForPhrp: undefined,
};

/** 빈 임대주택 1호 초기값 (토글 ON 시 자동 추가) */
export function makeDefaultRentalUnit(): AssetForm["rentalHousingException"]["rentalUnits"][number] {
  return {
    registrationDate: "",
    rentalType: "long-8",
    rentalAcquisitionType: "purchase",
    isApartment: false,
    region: "seoul-metro",
    standardPriceAtRentalStart: "",
    rentalMonths: "",
    rentalAutoTermination: false,
    requirementsConfirmed: false,
  };
}

/**
 * AssetForm 기본값 팩토리.
 * index === 1 인 경우 isPrimaryForHouseholdFlags = true 로 설정.
 */
export function makeDefaultAsset(index: number = 1): AssetForm {
  return {
    assetId: `asset-${Date.now()}-${index}`,
    assetLabel: `자산 ${index}`,
    assetKind: "housing",
    isSuccessorRightToMoveIn: false,
    isPrimaryForHouseholdFlags: index === 1,
    standardPriceAtTransfer: "",
    standardPriceAtTransferLabel: "",
    directExpenses: "0",
    capitalExpenditure: "0",
    transferExpense: "0",
    reductions: [],
    inheritanceValuationMode: "auto",
    inheritanceDate: "",
    inheritanceAssetKind: "land",
    acquisitionArea: "",
    transferArea: "",
    areaScenario: "same",
    publishedValueAtInheritance: "",
    fixedAcquisitionPrice: "",
    addressRoad: "",
    addressJibun: "",
    addressDetail: "",
    buildingName: "",
    longitude: "",
    latitude: "",
    isRegulatedAreaAtAcq: null,
    isRegulatedAreaAtTransfer: null,
    regionCode: undefined,
    parcelMode: false,
    parcels: [],
    isOneHousehold: false,
    ...RESIDENCE_DEFAULTS,
    actualSalePrice: "",
    ownershipNumerator: "100",
    ownershipDenominator: "100",
    acquisitionCause: "purchase",
    carryover: { ...CARRYOVER_DEFAULTS },
    acquisitionDate: "",
    assetContractDate: "", // Round 9 (2026-05-06): 매매계약일 (감면 시한 판정용)
    // 신축(자가건축) 취득일 4-시점 (영 §162①4호) — 사례 28 + G-5
    occupancyApprovalDate: "",
    approvalCertificateDate: "",
    temporaryApprovalDate: "",
    actualUseDate: "",
    // 부수토지 한도 산정 (영 §154⑦) — 사례 28
    isUrbanArea: undefined,
    appurtenantLandZone: undefined,
    // companion 토지 세율 수동 오버라이드 — 사례 28
    manualHoldingPeriodOverride: undefined,
    // 토지 자산 성격 — 부수토지 vs 독립 나대지 (사례 28 landNature 명시 입력 정책)
    landNature: undefined,
    decedentAcquisitionDate: "",
    donorAcquisitionDate: "",
    useEstimatedAcquisition: false,
    isAppraisalAcquisition: false,
    isSalesCaseAcquisition: false,
    similarSalesValue: "",
    similarSalesSource: undefined,
    acquisitionSigunguCode: "",
    isSelfBuilt: false,
    buildingType: "",
    constructionDate: "",
    extensionFloorArea: "",
    extensionStdPriceAtAcquisition: "",
    selfOwns: "both",
    hasSeperateLandAcquisitionDate: false,
    landAcquisitionDate: "",
    landSplitMode: "apportioned",
    usePreHousingDisclosure: false,
    phdFirstDisclosureDate: "",
    phdFirstDisclosureHousingPrice: "",
    phdLandPriceYearAtAcq: "",
    phdLandPriceYearAtAcqIsManual: false,
    phdLandPricePerSqmAtAcq: "",
    phdBuildingStdPriceAtAcq: "",
    phdLandPriceYearAtFirst: "",
    phdLandPriceYearAtFirstIsManual: false,
    phdLandPricePerSqmAtFirst: "",
    phdBuildingStdPriceAtFirst: "",
    phdTransferHousingPrice: "",
    phdLandPriceYearAtTransfer: "",
    phdLandPriceYearAtTransferIsManual: false,
    phdLandPricePerSqmAtTransfer: "",
    phdBuildingStdPriceAtTransfer: "",
    phdResidentialLandArea: "",
    phdCommercialBuildingStdPriceAtAcq: "",
    phdCommercialBuildingStdPriceAtFirst: "",
    landTransferPrice: "",
    buildingTransferPrice: "",
    landAcquisitionPrice: "",
    buildingAcquisitionPrice: "",
    landDirectExpenses: "",
    buildingDirectExpenses: "",
    landStandardPriceAtTransfer: "",
    buildingStandardPriceAtTransfer: "",
    standardPriceAtAcq: "",
    standardPriceAtAcqLabel: "",
    useStandardPriceAtAcqOverride: false,
    useStandardPriceAtTransferOverride: false,
    standardPricePerSqmAtAcq: "",
    standardPricePerSqmAtTransfer: "",
    inhHouseValEnabled: false,
    inhHouseValFirstDisclosureDate: "2005-04-30",
    inhHouseValLandArea: "",
    inhHouseValLandPricePerSqmAtTransfer: "",
    inhHouseValLandPricePerSqmAtFirst: "",
    inhHouseValLandPricePerSqmAtInheritance: "",
    inhHouseValHousePriceAtTransfer: "",
    inhHouseValHousePriceAtFirst: "",
    inhHouseValBuildingStdPriceAtTransfer: "",
    inhHouseValBuildingStdPriceAtFirst: "",
    inhHouseValBuildingStdPriceAtInheritance: "",
    inhHouseValUseHousePriceOverride: false,
    inhHouseValHousePriceAtInheritanceOverride: "",
    pre1990Enabled: false,
    pre1990PricePerSqm_1990: "",
    pre1990PricePerSqm_atTransfer: "",
    pre1990Grade_current: "",
    pre1990Grade_prev: "",
    pre1990Grade_atAcq: "",
    pre1990GradeMode: "number",
    replottingConfirmDate: "",
    entitlementArea: "",
    allocatedArea: "",
    priorLandArea: "",
    isNonBusinessLand: false,
    nblUseDetailedJudgment: false,
    nblLandType: "",
    nblZoneType: "",
    nblBusinessUsePeriods: [],
    nblLandSigunguCode: "",
    nblLandSigunguName: "",
    nblResidenceHistories: [],
    nblExemptInheritBefore2007: false,
    nblExemptInheritDate: "",
    nblExemptLongOwned20y: false,
    nblExemptAncestor8YearFarming: false,
    nblExemptPublicExpropriation: false,
    nblExemptPublicNoticeDate: "",
    nblExemptFactoryAdjacent: false,
    nblExemptJongjoongOwned: false,
    nblExemptJongjoongAcqDate: "",
    nblExemptUrbanFarmlandJongjoong: false,
    nblExemptInong: false,
    nblExemptInongDate: "",
    nblDeemedTransferReason: "none",
    nblDeemedTransferDate: "",
    nblUrbanIncorporationDate: "",
    nblIsMetropolitanArea: "",
    nblOwnershipRatio: "",
    nblFarmingSelf: false,
    nblFarmerResidenceDistance: "",
    nblFarmlandIsWeekendFarm: false,
    nblFarmlandIsConversionApproved: false,
    nblFarmlandConversionDate: "",
    nblFarmlandIsFarmDevZone: false,
    nblFarmlandIsMarginalFarm: false,
    nblFarmlandIsReclaimedLand: false,
    nblFarmlandIsPublicProjectUse: false,
    nblFarmlandIsSickElderlyRental: false,
    nblForestHasPlan: false,
    nblForestIsPublicInterest: false,
    nblForestIsProtected: false,
    nblForestIsSuccessor: false,
    nblForestInheritedWithin3Years: false,
    nblForestInheritanceDate: "",
    nblPastureIsLivestockOperator: false,
    nblPastureLivestockType: "",
    nblPastureLivestockCount: "",
    nblPastureLivestockPeriods: [],
    nblPastureInheritanceDate: "",
    nblPastureIsSpecialOrgUse: false,
    nblHousingFootprint: "",
    nblVillaUsePeriods: [],
    nblVillaIsEupMyeon: false,
    nblVillaIsRuralHousing: false,
    nblVillaBuildingFloorArea: "",
    nblVillaAttachedLandArea: "",
    nblVillaCombinedStdValue: "",
    nblVillaIsInRestrictedArea: false,
    nblVillaIsAfter20150101: false,
    nblOtherPropertyTaxType: "",
    nblOtherBuildingValue: "",
    nblOtherLandValue: "",
    nblOtherIsRelatedToResidence: false,
    nblOtherHasBuilding: false,
    nblOtherBuildingFloorArea: "",
    nblOtherMixedUseMode: "",
    nblOtherMixedUseSpecificFloorArea: "",
    nblOtherMixedUseTotalFloorArea: "",
    nblOtherMixedUseSpecificFootprint: "",
    nblOtherMixedUseTotalFootprint: "",
    nblOtherUseParcels: false,
    nblOtherParcels: [],
    nblOtherRelatedBusinessType: "",
    nblOtherStandardAreaLimit: "",
    nblOtherMaxAnnualArea: "",
    nblOtherYouthCapacity: "",
    nblOtherMinGarageArea: "",
    nblOtherSportsFacilityType: "", nblOtherReserveUnitSize: "", nblOtherReserveFacilities: [] as string[], nblOtherSportsCategory: "workplace", nblOtherEmployeeCount: "", nblOtherEmployeeFacilityKinds: [] as string[], nblOtherResortOutdoorArea: "", nblOtherResortParkingStdArea: "", nblOtherResortBuildingArea: "", nblOtherSportsPlayerCount: "", nblOtherIndoorNotInstalled: false, nblOtherSportsExtraEvents: [] as string[], nblOtherIndoorFloorArea: "", nblOtherResortBuildingFloorArea: "",
    nblRevenueBusinessType: "",
    nblRevenueCurrentRevenue: "",
    nblRevenueCurrentLandValue: "",
    nblRevenuePriorRevenue: "",
    nblRevenuePriorLandValue: "",
    nblGracePeriods: [],
    nblBusinessIsRealEstateDealer: false,
    inheritanceMode: null,
    inheritanceStartDate: "",
    hasDecedentActualPrice: false,
    decedentAcquisitionPrice: "",
    inheritanceReportedValue: "",
    inheritanceValuationMethod: "",
    inheritanceValuationEvidence: "",
    useSupplementaryHelper: false,
    supplementaryLandArea: "",
    supplementaryLandUnitPrice: "",
    supplementaryBuildingValue: "",
    ...MIXED_USE_DEFAULTS,
    rentalHousingException: { ...RENTAL_HOUSING_EXCEPTION_DEFAULTS },
    // ── 상업용건물·오피스텔 환산취득가 cb* 필드 (사례 29, 소득세법 시행령 §164⑧) ──
    cbEra: "",
    cbExclusiveArea: "",
    cbSharedArea: "",
    cbLandArea: "",
    cbUnitPriceAtTransfer: "",
    cbUnitPriceAtFirstOrAcq: "",
    cbBuildingStdPriceAtAcq: "",
    cbBuildingStdPriceAtFirst: "",
    cbBuildingStdPriceAtTransfer: "",
    cbLandPricePerSqmAtAcq: "",
    cbLandPricePerSqmAtFirst: "",
    cbLandPricePerSqmAtTransfer: "",
    // ── 일반건물(토지+건물 일괄) 환산취득가 gb* 필드 (사례 31, 소득세법 시행령 §176의2②, §163⑥) ──
    // 환산 ON/OFF는 useEstimatedAcquisition 라디오로 통일 (2026-05-09)
    gbTransferLandPricePerSqm: "",
    gbTransferBuildingValue: "",
    gbAcqLandPricePerSqm: "",
    gbAcqBuildingValue: "",
    gbLandArea: "",
    gbBuildingArea: "",
    gbBuildingFootprintArea: "",
    // ── 일반건물 비사업용토지 판정 (§104의3·§168의12, 2026-05-10) ──
    gbZoneType: "",
    gbIsMetropolitan: false,
    gbIsUnregistered: false,
    // ── 일반건물 건물 취득원인 + 건물 취득일 (사례 32 이후 PR) ──
    gbBuildingAcquisitionCause: undefined,
    gbBuildingAcquisitionDate: "",
    gbBundledAcquisitionExpenses: "",
    // ── 사례 33: 증축 건물 환산취득가 (소득세법 시행령 §176의2②, §166⑥) ──
    gbHasExtension: false,
    gbExtensionDate: "",
    gbExtensionArea: "",
    gbTransferExtensionBuildingStdPrice: "",
    gbAcquisitionExtensionBuildingStdPrice: "",
    gbExtensionAcquisitionCause: "newConstruction",
    gbExtensionAcquisitionMode: "estimated",   // 사례 33 호환 default
    gbExtensionActualAcquisitionPrice: "",
    gbExtensionActualExpenses: "",
    gbExtensionFloorArea85: "",
    // ── 사례 35: 주택→상가 용도변경 ──
    gbHouseToCommercialConversion: false,
    gbConversionDate: "",
    gbWasMultiHouseAtConversion: null,
    // ── 사례 35 후속-1: §99-164-10 환산주택가격 ──
    gbHasFirstDisclosure: false,
    gbFirstDisclosurePrice: "",
    gbFirstDisclosureLandStdPrice: "",
    gbFirstDisclosureBuildingStdPrice: "",
    // ── 부담부증여 (소령 §159, Phase 2: 모든 propertyType 지원) ──
    transferType: "regular",
    bgValuationMode: "",
    bgLendingDepositTotal: "",
    bgMortgageDebtAmount: "",
    bgAnnualRentTotal: "",
    bgMortgageSetAmount: "",
    bgMarketValueAtTransfer: "",
    bgMarketValueAtAcquisition: "",
    bgGiftBuildingStdPriceAtTransfer: "",
    // K-4/K-5 취득가액 산정방식 (시가 모드)
    bgAcquisitionMethod: "",
    bgActualAcquisitionLand: "",
    bgActualAcquisitionBuilding: "",
    bgActualAcquisitionTotal: "",
    // Phase 3: 증여세 통합 입력
    bgDonorRelation: "",
    bgIsMinorDonee: false,
    bgIsGenerationSkip: false,
    bgIsFiledOnTime: true,
    bgPriorGifts: [],
    // ── 재개발/재건축 (시행령 §166) — 사례 44 ──
    redevSubject: "",
    redevApprovalLawBasis: "",
    redevOriginalAssetType: "housing",
    redevSettlementDirection: "",
    redevApprovalDate: "",
    redevSettlementSaleDate: "",
    redevRightsValue: "",
    redevSettlementAmount: "",
    redevPreApprovalExpenses: "",
    redevPostApprovalExpenses: "",
    redevAcquisitionStdPrice: "",
    redevManagementDisposalStdPrice: "",
    redevFirstDisclosureDate: "",
    redevFirstDisclosureHousingPrice: "",
    redevFirstDisclosureStdPrice: "",
    // PHD 패턴 신규 필드
    redevLandArea: "",
    redevLandPricePerSqmAtAcq: "",
    redevBuildingStdPriceAtAcq: "",
    redevLandPricePerSqmAtFirst: "",
    redevBuildingStdPriceAtFirst: "",
    redevManagementDisposalHousingPrice: "",
    redevAcquisitionHousingPrice: "",
    redevActualAcquisitionPrice: "",
    // 사례 45 — 거주월수 분리 입력
    redevPriorHouseResidenceMonths: "",
    redevNewHouseResidenceMonths: "",
    // 거주기간 자동산정 입력 (입주일/퇴거일)
    redevPriorResidenceStartDate: "",
    redevPriorResidenceEndDate: "",
    redevNewResidenceStartDate: "",
    redevNewResidenceEndDate: "",
    // 사례 46 — 청산금 수령분 단독 신고
    redevReceiveOnlyMode: "",
    redevExemptionEligibleAtApproval: "",
    // 사례 36 — 1세대1입주권 비과세 C-1 안전장치
    redevPriorHouseHoldingMonths: "",
    // 사례 37 — 토지 출자 §166③ 환산 (subject="right" + originalAssetType="land")
    redevLandStdPriceAtAcq: "",      // @deprecated — legacy 총액 직접 입력 (sessionStorage 호환용)
    redevLandStdPriceAtApproval: "", // @deprecated — legacy 총액 직접 입력 (sessionStorage 호환용)
    redevLandPricePerSqmAtApproval: "", // §166③ 분모 ㎡당 단가 (LandPriceLookupField 신규 입력 경로)
    // 사례 38/39 — 단독주택 출자 §164⑤ PHD 2-point 환산취득가
    redevHousingStdPriceAtAcq: "",    // §164⑤ 분자 — 취득당시 개별주택가격
    redevHousingStdPriceAtApproval: "", // §164⑤ 분모 — 인가당시 부근 개별주택가격
    // 사례 48 — 승계조합원 신축APT 양도
    redevIsSuccessorMember: "",
    redevCompletionDate: "",
    // 가업상속공제 §97의2④ — UI 시니어 후속 위임. 미사용 시 undefined.
    familyBusinessInheritance: undefined,
  };
}

/** 하위 호환 별칭 */
export const makeDefaultCompanionAsset = makeDefaultAsset;
